"""add fav_category1 and fav_category2 to User

Revision ID: 438168e62fc3
Revises: c716d5f70634
Create Date: 2025-11-10 19:04:43.549474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438168e62fc3'
down_revision = 'c716d5f70634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_category1', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fav_category2', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fav_category2')
        batch_op.drop_column('fav_category1')

    # ### end Alembic commands ###
