"""add category field to Book

Revision ID: c716d5f70634
Revises: d3c3dd041f27
Create Date: 2025-11-10 15:48:52.420537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c716d5f70634'
down_revision = 'd3c3dd041f27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('books', schema=None) as batch_op:
              # Hacer la columna nullable inicialmente para evitar errores si ya hay datos en la tabla
              batch_op.add_column(
                     sa.Column('category', sa.String(length=50), nullable=True)
              )

              batch_op.alter_column(
                     'title',
                     existing_type=sa.VARCHAR(length=200),
                     type_=sa.String(length=120),
                     existing_nullable=False,
              )

              batch_op.alter_column(
                     'author',
                     existing_type=sa.VARCHAR(length=200),
                     type_=sa.String(length=120),
                     existing_nullable=False,
              )

              batch_op.alter_column(
                     'stock',
                     existing_type=sa.INTEGER(),
                     nullable=False,
              )

              batch_op.alter_column(
                     'cover_filename',
                     existing_type=sa.VARCHAR(length=300),
                     type_=sa.String(length=255),
                     existing_nullable=True,
              )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('cover_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
